name: CI

on: [push, pull_request]

jobs:
  CI:
    name: continuos integration
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x64]
        go: ['1.16']

    runs-on: ${{ matrix.os }}
    steps:

      - name: check out code
        uses: actions/checkout@v2

      - name: set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: build
        run: go build ./...

      - name: test
        run: go test ./... -race -covermode=atomic -coverprofile=coverage.txt .

      - name: coverage
        uses: codecov/codecov-action@v2.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt